import type { ArchEdge, ArchNode } from "./types";

const CONTEXT_NODES: ArchNode[] = [
  {
    id: "ctx.web",
    label: "Web UI",
    kind: "ui",
    layer: "context",
    group: "Client",
    anchor: "apps/web/src/App.tsx::App",
    summary:
      "React 19 + Vite single-page app. Routed shell: Chat, Organizations, Products, Graphs, Architecture. Refetches the message list after every send (no background polling) and renders draft/final contract cards.",
    reads: [
      "GET /api/customers",
      "GET /api/customers/{id}/messages",
      "GET /api/customers/{id}/graph",
      "GET /api/orgs",
      "GET /api/products",
      "GET /api/models",
    ],
    writes: ["POST /api/customers/{id}/messages"],
  },
  {
    id: "ctx.api",
    label: "FastAPI app",
    kind: "router",
    layer: "context",
    group: "Server",
    anchor: "apps/api/main.py::app",
    summary:
      "Wires every router: customers, products, chats, messages, models, organizations, graphs. CORS is restricted to WEB_ORIGIN. On startup a lifespan hook ensures the Mongo indexes and seeds the org roster.",
  },
  {
    id: "ctx.mongo",
    label: "MongoDB",
    kind: "store",
    layer: "context",
    group: "Stores",
    anchor: "apps/api/db/mongo.py::db",
    summary:
      "Live mutable state. Collections: customers, organizations, chats, messages, summaries, products. The current draft contract lives here as a pending summary until it is approved.",
    invariant: "Everything before finalize lives in Mongo, not the graph.",
  },
  {
    id: "ctx.falkor",
    label: "FalkorDB",
    kind: "store",
    layer: "context",
    group: "Stores",
    anchor: "apps/api/db/falkor.py::customer_graph",
    summary:
      "The knowledge graph — committed truth only. One graph per customer (customer:<id>); there is no shared catalog graph, the catalog lives in S3 Vectors. Contract data is written only at finalize time.",
    invariant:
      "Guarded by falkor.is_available() everywhere; if it is down, grounding is empty and the agent degrades to chat-only reasoning rather than erroring.",
  },
  {
    id: "ctx.vectors",
    label: "S3 Vectors",
    kind: "store",
    layer: "context",
    group: "Stores",
    anchor: "apps/api/db/vectors.py::S3VectorsIndex",
    summary:
      "The product catalog as embeddings — one index per organization, named {S3_VECTOR_INDEX}-{slug} and stored on the org document. The agent only ever queries the index belonging to the customer's org.",
    invariant:
      "is_available() is just \"is S3_VECTOR_BUCKET set\"; when it is not, the matcher falls back to a substring scan over Mongo so the app still works offline.",
  },
  {
    id: "ctx.llm",
    label: "LLM providers",
    kind: "external",
    layer: "context",
    group: "External",
    anchor: "core/llm_client.py::call_llm",
    summary:
      "Bedrock / Anthropic / OpenAI / Gemini behind one call. Uses instructor to coerce every response into a Pydantic schema. Model chosen per-request via model_key through core.utils.MODEL_CATALOG.",
  },
];

const CONTEXT_EDGES: ArchEdge[] = [
  { id: "ctx.e1", source: "ctx.web", target: "ctx.api", label: "HTTP /api", layer: "context", kind: "call" },
  { id: "ctx.e2", source: "ctx.api", target: "ctx.mongo", label: "orgs · chats · messages · summaries", layer: "context", kind: "data" },
  { id: "ctx.e3", source: "ctx.api", target: "ctx.falkor", label: "read graph · write contract", layer: "context", kind: "data" },
  { id: "ctx.e5", source: "ctx.api", target: "ctx.vectors", label: "build · query per-org index", layer: "context", kind: "data" },
  { id: "ctx.e4", source: "ctx.api", target: "ctx.llm", label: "structured calls", layer: "context", kind: "call" },
];

const FLOW_NODES: ArchNode[] = [
  {
    id: "flow.messages",
    label: "POST /messages",
    kind: "router",
    layer: "flows",
    group: "Entrypoints",
    flows: ["autonomous", "approve"],
    anchor: "apps/api/routers/messages.py::post_message",
    summary:
      "The only entrypoint. Appends one kind=\"chat\" message, then parses the body for an @agent tag and runs the agent when it finds one. Returns {messages, summary} either way.",
  },
  {
    id: "flow.agent_tag",
    label: "agent_tag.parse",
    kind: "gate",
    layer: "flows",
    group: "Entrypoints",
    flows: ["autonomous", "approve"],
    anchor: "apps/api/services/agent_tag.py::parse",
    summary:
      "Deterministic keyword gate. \"@agent confirm|finalize|approve\" → approve; any other \"@agent …\" → ask; untagged → the message is just appended.",
    invariant: "Finalization is never model-decided — only an explicit confirm word commits.",
  },
  {
    id: "flow.agent_service",
    label: "agent_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    flows: ["autonomous", "approve"],
    anchor: "apps/api/services/agent_service.py::invoke",
    summary:
      "The agent itself: invoke() drafts or asks, approve() finalizes, finalize() commits a decision directly. Reached only through an @agent tag on a chat message.",
    invariant: "Never auto-commits. A ready_to_finalize decision still only drafts.",
  },
  {
    id: "flow.chat_service",
    label: "chat_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    flows: ["autonomous", "approve"],
    anchor: "apps/api/services/chat_service.py::ensure_active_chat",
    summary:
      "Chat lifecycle and the message window. Assigns per-chat monotonic seq numbers, reuses or opens the active chat, and slices messages since the last contract watermark.",
  },
  {
    id: "flow.org_service",
    label: "org_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    flows: ["autonomous"],
    anchor: "apps/api/services/org_service.py::org_id_for_customer",
    summary:
      "Organization lookups: the roster, slugs, and which vector index an org owns. Raises MissingOrg when a customer or product reaches org-scoped code without an org_id.",
    invariant:
      "vector_index_name() reads the name stored on the org document, so changing S3_VECTOR_INDEX later cannot orphan existing vectors.",
  },
  {
    id: "flow.matcher",
    label: "product_matcher_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    flows: ["autonomous"],
    anchor: "apps/api/services/product_matcher_service.py::resolve_products",
    summary:
      "Resolves product mentions to catalog SKUs in two LLM calls: one extracts distinct mentions, one resolves them. The candidate pool is the customer's organization S3-Vectors index plus this customer's prior orders, and each mention comes back confident, ambiguous, or no_match.",
    invariant: "_guard() drops any resolved_code outside the pool — product codes are never invented.",
  },
  {
    id: "flow.context_service",
    label: "summary_context_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    flows: ["autonomous"],
    anchor: "apps/api/services/summary_context_service.py::assemble",
    summary:
      "Assembles grounding from FalkorDB: profile_block from Attribute nodes and history_block from Preference nodes, both None when FalkorDB is unavailable. product_block is left empty here — agent_service overwrites it with the resolved SKUs.",
  },
  {
    id: "flow.chat_graph",
    label: "chat_graph_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    flows: ["approve"],
    anchor: "apps/api/services/chat_graph_service.py::write_contract",
    summary:
      "The only writer of contract data into the customer graph. Creates the Contract subgraph and derives Preference nodes from both-agreed slots.",
  },
  {
    id: "flow.graph_reader",
    label: "graph_reader_service",
    kind: "service",
    layer: "flows",
    group: "Services",
    anchor: "apps/api/services/graph_reader_service.py::read_customer_graph",
    summary: "Reads one customer's graph into {nodes, edges} for the UI's Graphs tab. Returns an empty graph when FalkorDB is unreachable.",
  },
  {
    id: "flow.mongo",
    label: "MongoDB",
    kind: "store",
    layer: "flows",
    group: "Stores",
    flows: ["autonomous", "approve"],
    anchor: "apps/api/db/mongo.py::db",
    summary: "customers, organizations, products, chats, messages, summaries. The pending draft and the message window both live here.",
  },
  {
    id: "flow.falkor",
    label: "FalkorDB",
    kind: "store",
    layer: "flows",
    group: "Stores",
    flows: ["autonomous", "approve"],
    anchor: "apps/api/db/falkor.py::customer_graph",
    summary: "Read for grounding on every draft; written only on approve.",
  },
  {
    id: "flow.vectors",
    label: "S3 Vectors",
    kind: "store",
    layer: "flows",
    group: "Stores",
    flows: ["autonomous"],
    anchor: "apps/api/db/vectors.py::S3VectorsIndex",
    summary: "Per-org product embeddings. Queried top-5 per mention; falls back to a Mongo substring scan when unset or erroring.",
  },
  {
    id: "flow.llm",
    label: "core.llm_client",
    kind: "external",
    layer: "flows",
    group: "External",
    flows: ["autonomous"],
    anchor: "core/llm_client.py::call_llm",
    summary: "Schema-coerced LLM calls: MentionList and ProductMatchResult for matching, AgentDecision for drafting, plus OrgChoice and ProductSpec off the request path.",
  },
];

const FLOW_EDGES: ArchEdge[] = [
  { id: "flow.e1", source: "flow.messages", target: "flow.chat_service", label: "append chat message", layer: "flows", kind: "call" },
  { id: "flow.e2", source: "flow.messages", target: "flow.agent_tag", label: "@agent …", layer: "flows", flows: ["autonomous", "approve"], kind: "call" },
  { id: "flow.e3", source: "flow.agent_tag", target: "flow.agent_service", label: "ask | approve", layer: "flows", flows: ["autonomous", "approve"], kind: "call" },
  { id: "flow.e7", source: "flow.agent_service", target: "flow.chat_service", label: "window", layer: "flows", flows: ["autonomous", "approve"], kind: "call" },
  { id: "flow.e20", source: "flow.agent_service", target: "flow.org_service", label: "org_id_for_customer", layer: "flows", flows: ["autonomous"], kind: "call" },
  { id: "flow.e8", source: "flow.agent_service", target: "flow.matcher", label: "resolve products", layer: "flows", flows: ["autonomous"], kind: "call" },
  { id: "flow.e9", source: "flow.agent_service", target: "flow.context_service", label: "grounding", layer: "flows", flows: ["autonomous"], kind: "call" },
  { id: "flow.e10", source: "flow.agent_service", target: "flow.llm", label: "decide()", layer: "flows", flows: ["autonomous"], kind: "call" },
  { id: "flow.e11", source: "flow.agent_service", target: "flow.chat_graph", label: "write_contract", layer: "flows", flows: ["approve"], kind: "call" },
  { id: "flow.e14", source: "flow.chat_service", target: "flow.mongo", label: "chats · messages", layer: "flows", kind: "data" },
  { id: "flow.e15", source: "flow.agent_service", target: "flow.mongo", label: "upsert pending summary", layer: "flows", flows: ["autonomous", "approve"], kind: "data" },
  { id: "flow.e16", source: "flow.matcher", target: "flow.falkor", label: "prior orders", layer: "flows", flows: ["autonomous"], kind: "data" },
  { id: "flow.e21", source: "flow.matcher", target: "flow.vectors", label: "top-5 per mention", layer: "flows", flows: ["autonomous"], kind: "data" },
  { id: "flow.e22", source: "flow.matcher", target: "flow.mongo", label: "live codes · fallback scan", layer: "flows", flows: ["autonomous"], kind: "data" },
  { id: "flow.e23", source: "flow.org_service", target: "flow.mongo", label: "org roster", layer: "flows", flows: ["autonomous"], kind: "data" },
  { id: "flow.e17", source: "flow.context_service", target: "flow.falkor", label: "profile + preferences", layer: "flows", flows: ["autonomous"], kind: "data" },
  { id: "flow.e18", source: "flow.chat_graph", target: "flow.falkor", label: "Contract subgraph", layer: "flows", flows: ["approve"], kind: "data" },
  { id: "flow.e19", source: "flow.graph_reader", target: "flow.falkor", label: "read", layer: "flows", kind: "data" },
];

const AGENT_NODES: ArchNode[] = [
  {
    id: "agent.invoke",
    label: "invoke()",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/agent_service.py::invoke",
    summary: "Entry to the draft loop. Every dependency (decider, context_fn, graph_fn, matcher_fn) is injectable.",
  },
  {
    id: "agent.ensure_chat",
    label: "ensure_active_chat",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/chat_service.py::ensure_active_chat",
    summary: "Reuses the non-finished chat, or opens \"Chat N\".",
  },
  {
    id: "agent.window",
    label: "messages_since(watermark)",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/chat_service.py::messages_since",
    summary:
      "Slices messages after last_contract_seq, limited to kinds chat, question, draft, final.",
    invariant: "last_contract_seq is the watermark — after finalize it advances, so the next order reasons over a clean window.",
  },
  {
    id: "agent.gate_empty",
    label: "GATE · empty window",
    kind: "gate",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/agent_service.py::invoke",
    summary: "No new messages since the last contract → post a plain chat message and return.",
  },
  {
    id: "agent.gate_noorg",
    label: "GATE · customer has no org",
    kind: "gate",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/org_service.py::MissingOrg",
    summary:
      "org_id_for_customer raises MissingOrg → post a question telling the user to assign an organization on the Organizations page, and return. Product lookup is org-scoped, so there is no catalog to search without one.",
  },
  {
    id: "agent.match",
    label: "resolve_products",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/product_matcher_service.py::resolve_products",
    summary:
      "Pins every product mention to a SKU in the customer's own organization catalog before any drafting happens. Prior-order codes from the graph are filtered to that org's live codes first, so another org's SKUs can never enter the pool.",
  },
  {
    id: "agent.gate_unresolved",
    label: "GATE · unresolved products",
    kind: "gate",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/agent_service.py::_match_question",
    summary: "Any ambiguous or unmatched mention → post a question card asking which SKU, and return.",
    invariant: "The agent will not draft until products are pinned down.",
  },
  {
    id: "agent.context",
    label: "assemble context",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/summary_context_service.py::assemble",
    summary:
      "profile_block from graph Attribute nodes, history_block from Preference nodes. agent_service then overwrites product_block with the resolved SKUs, so the model sees the pinned catalog rows rather than the whole catalog.",
  },
  {
    id: "agent.previous",
    label: "load pending draft",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/agent_service.py::_pending",
    summary: "An existing pending summary is passed back to the model as previous_json so drafts revise rather than restart.",
  },
  {
    id: "agent.decide",
    label: "decide() → AgentDecision",
    kind: "external",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/agent_service.py::decide",
    summary:
      "The LLM call. Returns mode, message, questions, contract, ledger, ready_to_finalize. Questions are capped at 3 with critical slots first.",
    invariant: "mode==\"finalize\" without readiness is downgraded to \"draft\".",
  },
  {
    id: "agent.verify",
    label: "verify(decision)",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/verification.py::verify",
    summary:
      "Deterministic verification gate over the model's decision before anything is drafted. Checks product-code grounding (a line item's description must be a matcher-resolved SKU or name), ship_term ∈ {EXW,FOB,CIF,DDP}, total == quantity×unit_price, ISO dates, and per-slot provenance (source, source_seqs). Blocking violations become a question; warnings are stored on the draft.",
    invariant:
      "Blocking codes (unknown_product_code, bad_ship_term, critical_unknown_source) stop a draft; warnings (total_mismatch, bad_date_format, missing_provenance, stale_citation) are recorded, not fatal.",
  },
  {
    id: "agent.gate_verify",
    label: "GATE · blocking violation",
    kind: "gate",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/verification.py::has_blocking",
    summary:
      "A blocking violation (ungrounded product, bad incoterm, or a critical slot with source='unknown') → post a question listing the problems, write no summary, and return.",
  },
  {
    id: "agent.gate_clarify",
    label: "GATE · mode == clarify",
    kind: "gate",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/services/agent_service.py::invoke",
    summary: "The model needs answers → post a question card, write no summary, and return.",
  },
  {
    id: "agent.draft",
    label: "upsert draft + post card",
    kind: "service",
    layer: "agent",
    group: "Draft pipeline",
    flows: ["autonomous"],
    anchor: "apps/api/models.py::render_summary_markdown",
    summary:
      "Renders the contract to markdown, upserts the pending summary with slots, product_matches and any verification warnings, bumps revision, posts a draft card.",
    invariant: "A ready decision still only drafts — it appends \"Ready to finalize\" and waits for @agent confirm.",
  },
  {
    id: "agent.approve",
    label: "approve()",
    kind: "service",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/services/agent_service.py::approve",
    summary: "The only path that writes a contract to the graph.",
  },
  {
    id: "agent.gate_nodraft",
    label: "GATE · no pending draft",
    kind: "gate",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/services/agent_service.py::approve",
    summary: "Nothing to finalize → reply telling the user to run @agent create sales order first.",
  },
  {
    id: "agent.gate_ready",
    label: "GATE · is_ready(slots)",
    kind: "gate",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/models.py::is_ready",
    summary:
      "The hard commit gate. Every critical slot (description, quantity, unit_price, ship_term) must be agreed by BOTH seller and customer. Otherwise reply listing what is missing and stop.",
    invariant: "This is the single gate preventing an unagreed contract from reaching the graph.",
  },
  {
    id: "agent.verify_commit",
    label: "verify(pending)",
    kind: "service",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/verification.py::verify",
    summary:
      "The same deterministic verifier, re-run on the stored pending draft at commit time (resolved_codes=None, so product grounding is trusted from draft time). A blocking violation refuses the finalize.",
    invariant: "is_ready proves both parties agreed; verify proves the contract is well-formed. Both must pass before write_contract.",
  },
  {
    id: "agent.gate_verify_commit",
    label: "GATE · failed verification",
    kind: "gate",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/verification.py::has_blocking",
    summary:
      "The pending draft failed verification → reply listing the blocking problems and stop, without writing the graph.",
  },
  {
    id: "agent.write",
    label: "write_contract",
    kind: "service",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/services/chat_graph_service.py::write_contract",
    summary:
      "Creates Contract, one LineItem per item, Term nodes, and SUPERSEDES to the prior revision. Writes per-slot MessageRef provenance: each LineItem/Term gets DERIVED_FROM edges to the exact messages its slots cite (source_seqs). Derives a Preference node for every both-agreed slot.",
    invariant: "Preferences are the feedback loop — they reappear as history_block grounding on the next draft.",
  },
  {
    id: "agent.persist",
    label: "persist + final card",
    kind: "service",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/services/agent_service.py::_persist_final",
    summary: "Flips the summary to approved and advances chat.last_contract_seq to the draft's to_seq.",
  },
  {
    id: "agent.branch",
    label: "_finish_and_branch",
    kind: "service",
    layer: "agent",
    group: "Commit pipeline",
    flows: ["approve"],
    anchor: "apps/api/services/agent_service.py::_finish_and_branch",
    summary:
      "Marks the chat finished, opens \"Chat N+1\", and links newChat -CONTINUES-> oldChat. Renders in the UI as the contract-finalized checkpoint divider.",
  },
];

const AGENT_EDGES: ArchEdge[] = [
  { id: "agent.e1", source: "agent.invoke", target: "agent.ensure_chat", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e2", source: "agent.ensure_chat", target: "agent.window", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e3", source: "agent.window", target: "agent.gate_empty", label: "no new messages", layer: "agent", flows: ["autonomous"], kind: "gate-fail" },
  { id: "agent.e17", source: "agent.window", target: "agent.gate_noorg", label: "customer has no org_id", layer: "agent", flows: ["autonomous"], kind: "gate-fail" },
  { id: "agent.e4", source: "agent.window", target: "agent.match", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e5", source: "agent.match", target: "agent.gate_unresolved", label: "ambiguous / no_match", layer: "agent", flows: ["autonomous"], kind: "gate-fail" },
  { id: "agent.e6", source: "agent.match", target: "agent.context", label: "all confident", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e7", source: "agent.context", target: "agent.previous", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e8", source: "agent.previous", target: "agent.decide", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e9", source: "agent.decide", target: "agent.gate_clarify", label: "needs answers", layer: "agent", flows: ["autonomous"], kind: "gate-fail" },
  { id: "agent.e10", source: "agent.decide", target: "agent.verify", label: "draft | finalize", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e18", source: "agent.verify", target: "agent.gate_verify", label: "ungrounded / malformed", layer: "agent", flows: ["autonomous"], kind: "gate-fail" },
  { id: "agent.e19", source: "agent.verify", target: "agent.draft", label: "clean / warnings stored", layer: "agent", flows: ["autonomous"], kind: "call" },
  { id: "agent.e11", source: "agent.draft", target: "agent.approve", label: "@agent confirm (separate request)", layer: "agent", flows: ["approve"], kind: "data" },
  { id: "agent.e12", source: "agent.approve", target: "agent.gate_nodraft", label: "no pending summary", layer: "agent", flows: ["approve"], kind: "gate-fail" },
  { id: "agent.e13", source: "agent.approve", target: "agent.gate_ready", layer: "agent", flows: ["approve"], kind: "call" },
  { id: "agent.e14", source: "agent.gate_ready", target: "agent.verify_commit", label: "all critical slots agreed", layer: "agent", flows: ["approve"], kind: "call" },
  { id: "agent.e20", source: "agent.verify_commit", target: "agent.gate_verify_commit", label: "failed verification", layer: "agent", flows: ["approve"], kind: "gate-fail" },
  { id: "agent.e21", source: "agent.verify_commit", target: "agent.write", label: "verified", layer: "agent", flows: ["approve"], kind: "call" },
  { id: "agent.e15", source: "agent.write", target: "agent.persist", layer: "agent", flows: ["approve"], kind: "call" },
  { id: "agent.e16", source: "agent.persist", target: "agent.branch", layer: "agent", flows: ["approve"], kind: "call" },
];

export const NODES: ArchNode[] = [...CONTEXT_NODES, ...FLOW_NODES, ...AGENT_NODES];
export const EDGES: ArchEdge[] = [...CONTEXT_EDGES, ...FLOW_EDGES, ...AGENT_EDGES];

export function nodesForLayer(layer: string): ArchNode[] {
  return NODES.filter((n) => n.layer === layer);
}

export function edgesForLayer(layer: string): ArchEdge[] {
  return EDGES.filter((e) => e.layer === layer);
}
