from typing import Protocol, runtime_checkable


@runtime_checkable
class AbstractGraphBackend(Protocol):
    def write_episode(self, episode: dict) -> bool: ...
    def query_customer(self, customer_id: str) -> list[dict]: ...
    def close(self) -> None: ...
